Replaced all references to timehop by adsbynimbus
adsbynimbus/nimbus-unity pull request #44
Opened 2023-09-14 21:45 UTC by brugg

2023-09-14 21:45 UTC, inderdhir approved these changes

2023-09-14 21:50 UTC, marcsantiago commented on com.adsbynimbus.nimbus/package.json
> +    "email": "marc@adsbynimbus.com",
should marc@nimbus.co

2023-09-14 21:55 UTC, marcsantiago commented
This package hasn't been migrated to the adsbynimbus org...  You migrate first AND then update references.

2023-09-14 21:57 UTC, marcsantiago requested changes
This package hasn't been migrated to the adsbynimbus org... You migrate first AND then update references typically. For Likewise, moving to the new reference means an update in Unity installation docs are needed.

2023-09-14 22:03 UTC, brugg commented on com.adsbynimbus.nimbus/package.json
> +    "email": "marc@adsbynimbus.com",
True. Thanks

2023-09-29 20:32 UTC, marcsantiago approved these changes

2023-09-29 20:32 UTC, merged